### ISSUE TITLE
Headless components

### ISSUE THREAD

**Issue by hoangvu12** [malerba118/supabase-comments-extension#7]
I think we should have headless components for those who are wanted to use their own styling.

**Comment by malerba118** [comment]
There are 14 hooks exported from the lib which manage all of the data fetching via react-query.

https://github.com/malerba118/supabase-comments-extension/tree/main/src/hooks

I recommend you use those if you want to build your own ui!

**Comment by hoangvu12** [comment]
> There are 14 hooks exported from the lib which manage all of the data fetching via react-query.
> 
> https://github.com/malerba118/supabase-comments-extension/tree/main/src/hooks
> 
> I recommend you use those if you want to build your own ui!

Thank you, also can you do optimistic update on add comment and add reaction? I can make a PR if you want.

**Comment by malerba118** [comment]
Sounds like a good idea, but yeah a pr would definitely be appreciated!

**Comment by hoangvu12** [comment]
> Sounds like a good idea, but yeah a pr would definitely be appreciated!

I'm trying to setup dev enviroment but can't seem to do it. Can you provide more details how to do that?

**Comment by malerba118** [comment]
there's two processes you have to run

process to compile the src and pipe it into the dist folder
```
# within root of repo
npm install
npm start
```

process to run server for example app
```
# within example folder
npm install
npm start
```

then if you change anything in the library it should auto-recompile and put it in the dist folder and hot-reload the example app (which i think will be running on either localhost:3000 or localhost:3001)

**Comment by hoangvu12** [comment]
I'm using Windows so set env variable directly in the script won't work, maybe you could use cross-env instead

![image](https://user-images.githubusercontent.com/68330291/181309322-12ebdb03-7d29-4831-8153-6f9f9d72d1f6.png)
